version: '3.8'

services:
  # フロントエンド
  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # Viteのデフォルトポート
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Windows/Macでホットリロードが効かない場合の対策
    stdin_open: true # インタラクティブモードを有効化
    tty: true
  
  minio:
    image: minio/minio
    ports:
      - "9005:9000" # API用
      - "9001:9001" # 管理画面(Console)用
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

# Python MLサービス (AI解析用)
  python-ml:
    build: ./python-ml
    ports:
      - "50051:50051"
    volumes:
      - ./python-ml:/app

# Goアプリケーションサービス
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db          
      - DB_PORT=5432
      - DB_USER=mydestinyuser  
      - DB_PASSWORD=mypassword 
      - DB_NAME=destiny_db
      # MinIO設定を追加
      - AWS_S3_ENDPOINT=http://minio:9000
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    command: go run cmd/main.go
    depends_on:
      db:
          condition: service_healthy
      redis:
          condition: service_started
      minio:
          condition: service_started

# PostgreSQLデータベースサービス (ユーザー情報、顔データ保存用)
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=mydestinyuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=destiny_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mydestinyuser -d destiny_db"]
      interval: 5s
      timeout: 5s
      retries: 5

# Redisサービス (認証データ保存用) redisがサービス名
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"